
name: "Deploy Web Page React"

on:
 push: 
    branches: [ master ] 
 pull_request: 
    branches: [ master ]

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Dependencies
      run: npm install
      working-directory: './Cobro Matricula Front-End/cobro-matricula'
    # - name: Run tests
    # - run: npm test
    - name: Build file
      run: npm run build

    # copy file for netlify.toml
    - name: Copy build settings to build folder
      run: cp netlify.toml build/

      # deploy application to netlify
    - name: Deploy production to Netlify
      uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.REACT_APP_API_URL }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './build'
        comment-on-commit: true
