
name: "Deploy Web Page React"

on:
 push: 
    branches: [ master ] 
 pull_request: 
    branches: [ master ]

permissions:
  contents: write # access to check out code and install dependencies

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Dependencies
      run: npm install
      working-directory: './Cobro Matricula Front-End/cobro-matricula'
    # - name: Run tests
    # - run: npm test
    - name: Build file
      run: npm run build
      working-directory: './Cobro Matricula Front-End/cobro-matricula'

    # copy file for netlify.toml
    - name: Copy build settings to build folder
      run: cp netlify.toml build/
      working-directory: './Cobro Matricula Front-End/cobro-matricula'

      # deploy application to netlify
    - name: Deploy production to Netlify
      uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './Cobro Matricula Front-End/cobro-matricula/build'
        comment-on-commit: true

# En la seccion de 'permissions' se debe permitir que se sobreescriba para poder desplegar el proyecto de React en Netlify
# Ademas se debe considerar que se debe generar un archivo netlify.toml con el siguiente contenido
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200 

# En el proceso de instalaccion se debe considerar que el comando: npm ci no funciona de forma adecuada si no se coloca el working-directory
# ya que de no colocarlo este no va a permitir la ejecucion del ese comando. En este caso se realizo la ejecucion del comando: npm install 
# con el respectivo working-directory

# Asi mismo, se debe colocar el working-directory en el proceso de build para que puede acceder al acrhivo de package.json

# En el caso del Deploy se debe agregar el path completo para que pueda acceder al archivo /publish que se genera en el proceso de copiar el 
# archivo de netlify.toml

# Tambien, se debe considerar que se debe configurar con las versiones compatibles en actions/checkout y setup-node para que se puedan ejecutar
# los comandos de forma correcta.